env:
  - RAKE_TASK=cucumber
  - RAKE_TASK=spec
language: ruby
before_install:
  - rake --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev
before_script:
  - bundle exec rake --version
script: "bundle exec rake $RAKE_TASK"

rvm:
  #- '1.8.7'
  - '1.9.3'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 5
